[[redirects]]
  from = "https://www.aiacademyforbeginners.com/*"
  to = "https://aiacademyforbeginners.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/7-inspiring-secrets-from-sam-onigbanjo-gtm-architects"
  to = "/about-sam-onigbanjo/"
  status = 301

[[redirects]]
  from = "/7-inspiring-secrets-from-sam-onigbanjo-gtm-architects/"
  to = "/about-sam-onigbanjo/"
  status = 301

[[redirects]]
  from = "/about-sam-onigbanjo"
  to = "/about-sam-onigbanjo.html"
  status = 200

[[redirects]]
  from = "/about-sam-onigbanjo/"
  to = "/about-sam-onigbanjo.html"
  status = 200

[[redirects]]
  from = "/community-impact"
  to = "/community-impact.html"
  status = 200

[[redirects]]
  from = "/community-impact/"
  to = "/community-impact.html"
  status = 200

[build]
  publish = "."

[[redirects]]
  from = "/ai_blogs"
  to = "/ai_blogs.html"
  status = 200

[[redirects]]
  from = "/ai_blogs/"
  to = "/ai_blogs.html"
  status = 200

[[redirects]]
  from = "/terms-and-conditions"
  to = "/terms-and-conditions.html"
  status = 200

[[redirects]]
  from = "/terms-and-conditions/"
  to = "/terms-and-conditions.html"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/privacy-policy/"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/refund-policy"
  to = "/refund-policy.html"
  status = 200

[[redirects]]
  from = "/refund-policy/"
  to = "/refund-policy.html"
  status = 200

[[redirects]]
  from = "/cookie-policy"
  to = "/cookie-policy.html"
  status = 200

[[redirects]]
  from = "/cookie-policy/"
  to = "/cookie-policy.html"
  status = 200

[[redirects]]
  from = "/disclaimer"
  to = "/disclaimer.html"
  status = 200

[[redirects]]
  from = "/disclaimer/"
  to = "/disclaimer.html"
  status = 200

[[redirects]]
  from = "/contract-opportunities"
  to = "/contract-opportunities.html"
  status = 200

[[redirects]]
  from = "/contract-opportunities/"
  to = "/contract-opportunities.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
